# Lattice Building with mBuild

This tutorial will walk you through building custom unit cells using the mBuild feature `Lattice`.

The beginning of this tutorial will describe the basics of the unit cell and lattice in the physical and crystallographic terms. From there, we will delve into the mBuild implementation of this feature and how to build your own cells.


# Lattice and Crystallographic Definitions
>Crystalline matter has particles that are arranged in a repeating pattern over long distances (_long range order_).

Long range, repeating order is the trademark of any type of crystalline structure. This can be present in any length scale, from the nanoscale to the macroscale.

Due to their general low energy states, many elements and molecules will crystallize when transforming into a solid. Crystalline materials are a very popular topic for investigation in the nanosciences and many simulation toolkits provide a lattice building tool due to the high demand.

These toolkits also make the process of placing atoms/molecules/particles in these repeatable lattice structures a much simpler affair. The ultimate goal of these toolkits are to reduce the complexity and difficulty of building large, complex structures and to do so very quickly. 

This is a large part of the overarching goal of `mBuild` as you all have hopefully seen by now.

## Definitions
**Unit Cell** - Smallest subunit of the lattice that, when repeated, will form the lattice

**Lattice** - Repeating framework of points in space that form the crystalline structure

**Crystal** - Structure formed when placing molecules/atoms/etc on the lattice

**[Bravais Lattice](https://en.wikipedia.org/wiki/Bravais_lattice)** - Framework formed by a discrete set of translations 

**Lattice Families** - Lattices defined by the location of their centering lattice points (Simple, Face Centered, Body Centered, etc.)

**Cell Definition** - required definitions to fully define a unit cell
   - **Edge Lengths** - lengths of the unit cell (a,b,c)
   - **Edge Vectors** - Vectors defining the bounding edges of the unit cell
   - **Interfacial Angles** - Angles of the edge vectors between one another ($\alpha$, $\beta$, $\gamma$)
   
**Basis Set** - Minimal set of fractional coordinates to denote location of lattice points
    - Ex) Simple Cubic - (0,0,0) is the only basis position, BCC - ( (0,0,0), (.5,.5,.5)) has 2 basis positions
    

Let's now jump in to the mBuild version of the Lattice!

# Example 1: Simple Cubic

To begin, lets work with a very simple example, a simple cubic cell.

Follow [this link](https://www.lahc.edu/classes/chemistry/arias/Exp%2011%20-%20Crystal%20StructureF11.pdf) to view the structure for the various cubic unit cells, including the Simple Cubic(SC).

Before we jump in to making our unit cell, lets take a look at the document string for the Lattice class itself.

In [1]:
import mbuild as mb
import nglview

This can be completed by running the `help()` command in python on the class or function you want to learn more about.

In [2]:
help(mb.Lattice)

Help on class Lattice in module mbuild.lattice:

class Lattice(builtins.object)
 |  Develop crystal structure from user defined inputs.
 |  
 |  Lattice, the abstract building block of a crystal cell.
 |  Once defined by the user, the crystal is returned as
 |  a single Compound that can be either replicated through its class
 |  methods or through a similar replicate Compound method.
 |  
 |  Lattice is defined through the standard bravais lattices, which have been
 |  accepted by the International Union of Crystallography.
 |  A Lattice can be fully described with its lattice vectors and lattice
 |  spacings. Also, the Lattice can be fully defined by its lattice parameters:
 |  the lattice spacings and its set of coordinate angles will then
 |  generate the lattice vectors. Lattice expects a right handed lattice and
 |  cell edges defined by vectors all originating from the origin in
 |  Cartesian space.
 |  
 |  Parameters
 |  ----------
 |  dimension : int, optional, default=3
 |  

We should see above that the only required argument is the `lattice_spacing` argument (**edge lengths**).

However, it dosent hurt to actually define your system a bit more verbosely, which is what this first example will cover.

Since our unit cell is a *cubic* cell, we should already know a bit about the edge lengths of the unit cell and its interfacial angles.
* All its edge lengths are the same value
* All its interfacial angles are 90$^\circ$

Finally, we should also know a bit about the basis set for the cell also.
* Only one basis position at (0,0,0)

Since this is a very inefficient unit cell packing compared to other types, not many elements exist in this state naturally. In fact, only one element does, [polonium](http://www.periodictable.com/Elements/084/data.html)

This link above provides the unit cell information needed to build this cell.

* The edge lengths are .3359nm

Now, lets build this in `mBuild`!

If we look back at the examples located in the help text for the `Lattice` class, we see that to make the lattice we need a few things:
1. Lattice spacings
2. Dimension
3. Lattice_vectors(or angles)
4. Basis set dictionary

Most of these values will default to values you will most likely use, but for the sake of these examples, we will define each one as verbosely as possible.

To begin, lets just define the 3 variables we know offhand: spacings, dimension, and vectors.

In [3]:
dim = 3
edge_lengths = [.3359, .3359, .3359]
lattice_vecs = [[1,0,0], [0,1,0], [0,0,1]]

Those values are all pretty easy to set, but the one that might need a bit more work is the basis dictionary.

This is essentially allowing us to link a unique name to each basis postion in the lattice. For the example we are working on, we only have one basis position, which makes things much simpler. Using the name "origin", will define our name to link to the (0,0,0) position.

In [4]:
basis = {'origin':[[0,0,0]]}

This data structure is a dictionary. Our key is 'origin', and our values are a list of lists, which contain the coordinates of the basis positions in the unit cell.

Next, lets put this all together and make our simple cubic lattice!

In [5]:
simple_cubic = mb.Lattice(edge_lengths, lattice_vectors=lattice_vecs, dimension=dim, basis_atoms=basis)

Success!

However, this is just the lattice with its lattice points, we still need to make the polonium crystal. How do we do that?

We `populate()` the polonium atoms on the basis positions in the unit cells and replicate them as many times as we want in the x, y, and z directions!

First, we need to make another dictionary which links the name we chose earlier for the basis position ('origin') to an `mBuild Compound` which will be placed on each of these locations.

So we need:
1. Compound for polonium atom
2. dictionary for relation to basis_atom dictionary

In [6]:
po = mb.Compound(name='Po')
compound_dictionary = {'origin':po}

Now, lets populate out our unit cell 3 times in each x,y,z direction and then visualize it!

Note that the `populate()` method returns a single `Compound` for the entire crystal you build here.

In [7]:
crystal_polonium = simple_cubic.populate(compound_dict=compound_dictionary, x=3, y=3, z=3)
crystal_polonium.visualize()

/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecat

# Stepping it up: Face Centered Copper

Now that we have the basics covered, we will work through one slightly more complex example.

Most elements naturally occur in the face centered cubic crystal system.

We will cover this system using [copper](http://www.periodictable.com/Elements/029/data.html).

Copper has:
1. Edge lengths of .36149 nm
2. 4 atoms per unit cell located at: (0, 0, 0), (.5, .5, 0), (0, .5, .5), (.5, 0, .5)

To begin, we initialize everything like before, but our basis dictionary will have 4 lists nested for our key.

In [10]:
dim = 3
copper_lengths = [.36149, .36149, .36149]
copper_vectors = [[1,0,0], [0,1,0], [0,0,1]]
copper_basis = {'Cu':[[0,0,0], [.5, .5, 0], [.5, 0, .5], [0, .5, .5]]}
copper_lattice_fcc = mb.Lattice(copper_lengths, dimension=dim,
                                lattice_vectors=copper_vectors, basis_atoms=copper_basis)

Now, lets expand out 3 in all directions again and visualize

In [11]:
cu = mb.Compound(name='Cu')
copper_dict = {'Cu':cu}
copper_crystal = copper_lattice_fcc.populate(compound_dict=copper_dict, x=3, y=3, z=3)
print(type(copper_lattice_fcc))
copper_crystal.visualize()

<class 'mbuild.lattice.Lattice'>


/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecat

# Final Example: Mixed Basis BCC
In the final example we will walk through a simple example with [Cesium Chloride](http://departments.kings.edu/chemlab/animation/cscl.html).

As shown above, CsCl has the structure of a BCC crystal, but due to the size difference between Cs and Cl, crystallographers consider it a simple cubic cell.

When making it in `mBuild` we will consider it as a bcc cell with Cs on the origin and Cl at (.5, .5, .5)

In [96]:
dim = 3
cscl_lengths = [.4123, .4123, .4123]
cscl_vectors = [[1,0,0], [0,1,0], [0,0,1]]
cscl_basis = {'Cs':[[0, 0, 0]], 'Cl':[[.5, .5, .5]]}
cscl_lattice = mb.Lattice(cscl_lengths, dimension=dim,
                                lattice_vectors=cscl_vectors, basis_atoms=cscl_basis)
cs = mb.Compound(name='Cs')
cl = mb.Compound(name='Cl')
cscl_dict = {'Cs':cs, 'Cl':cl}
#cscl_crystal = cscl_lattice.populate(compound_dict=cscl_dict, x=3, y=3, z=3)
cscl_crystal = cscl_lattice.populate(compound_dict=cscl_dict, x=2, y=2, z=2)

cscl_crystal.visualize()

sad


/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecated. Please use Compound.translate()
  warn(printed_message, DeprecationWarning)
/home/witteaj/builds/mbuild/mbuild/utils/decorators.py:11: DeprecationWarning: translate is deprecat

In [79]:
# from here down it is just me trying to label a better cube

import numpy as np
for part in cscl_crystal:
    if np.array_equal([0,0,0], part.pos):
        print(part.pos)
        print(type(cscl_crystal))
        print(part.name)
        part.name='Rb'
        
    if np.sum([1.0308,1.0308,1])<= np.sum(part.pos):
        print(part.pos)
        print(type(cscl_crystal))
        print(part.name)
        part.name='F'
        
    if part.pos[0] == 0 and part.pos[1] == 0 and .1<= part.pos[2]<=.5:
        print(part.pos)
        print(type(cscl_crystal))
        print(part.name)
        part.name='Fr'

cscl_crystal.visualize()
cscl_crystal.save('cscl_crystal_labels.mol2', overwrite = True)

[ 0.  0.  0.]
<class 'mbuild.compound.Compound'>
Rb
[ 0.      0.      0.4123]
<class 'mbuild.compound.Compound'>
Fr


In [80]:
for part in cscl_crystal:
    print(part)

<Rb pos=( 0.0000, 0.0000, 0.0000), 0 bonds, id: 140673877043352>
<Fr pos=( 0.0000, 0.0000, 0.4123), 0 bonds, id: 140673878726528>
<Cs pos=( 0.0000, 0.4123, 0.0000), 0 bonds, id: 140673877006096>
<Cs pos=( 0.0000, 0.4123, 0.4123), 0 bonds, id: 140673877006320>
<Cs pos=( 0.4123, 0.0000, 0.0000), 0 bonds, id: 140673877006488>
<Cs pos=( 0.4123, 0.0000, 0.4123), 0 bonds, id: 140673877006656>
<Cs pos=( 0.4123, 0.4123, 0.0000), 0 bonds, id: 140673877006824>
<Cs pos=( 0.4123, 0.4123, 0.4123), 0 bonds, id: 140673877006992>
<Cl pos=( 0.2061, 0.2061, 0.2061), 0 bonds, id: 140673877007160>
<Cl pos=( 0.2061, 0.2061, 0.6184), 0 bonds, id: 140673887302880>
<Cl pos=( 0.2061, 0.6184, 0.2061), 0 bonds, id: 140673877007496>
<Cl pos=( 0.2061, 0.6184, 0.6184), 0 bonds, id: 140673887303384>
<Cl pos=( 0.6184, 0.2061, 0.2061), 0 bonds, id: 140673877007776>
<Cl pos=( 0.6184, 0.2061, 0.6184), 0 bonds, id: 140673887304392>
<Cl pos=( 0.6184, 0.6184, 0.2061), 0 bonds, id: 140673877007328>
<Cl pos=( 0.6184, 0.6184,

In [81]:
cscl_crystal.save('cscl_crystal_label_p2.hoomdxml', overwrite = True)

In [98]:
type(cscl_lattice.lattice_vectors)
print(cscl_lattice.lattice_vectors)
updated_lat_vecs = [ii for ii in cscl_lattice.lattice_vectors]
print(np.array(updated_lat_vecs))



[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
